### ISSUE TITLE
Controls don't work on beta 2

### ISSUE THREAD

**Issue by SomeGuyWhoLovesCoding** [MaybeMaru/Maru-Funkin#25]
I'm in the title screen and I'm pressing every single key. It turns out that the enter key doesn't fuckin work. I've been waiting to play beta 2 for a long time and finally it came out on new year's.

**Comment by MaybeMaru** [comment]
markiplier
![image](https://github.com/MaybeMaru/Maru-Funkin/assets/97055307/ce612f65-7858-43d6-9b34-68c6d5a48bcf)

**Comment by MaybeMaru** [comment]
fr tho imma need some extra stuff to be able to do anything about this
do some testing in source first, nobody has ever had this issue and i cant replicate it

**Comment by MaybeMaru** [comment]
closed due to inactivity
