### ISSUE TITLE
Repeating Event Text

### ISSUE THREAD

**Issue by AnAmmar** [MaybeMaru/Maru-Funkin#26]
**Describe the bug**
The bug where the Event's text is repeated 8 times!

**To Reproduce**
Go To Charts Editor
Add An Events

**Media**
![image_2024-01-20_154648428](https://github.com/MaybeMaru/Maru-Funkin/assets/98030475/0e733c2b-7157-4026-a064-18c22b458738)

**Debug Crash Line**
There is Crash

**Additional context**
I ported the chart with events from Mario Madness. I'm trying to recreate Unbeatable using this engine.

**Comment by MaybeMaru** [comment]
The repeating text is because of the event being a stacked event, could you send the chart file or a zip containing the song?

**Comment by AnAmmar** [comment]
Sure. this is the chart
[have beat able chart.zip](https://github.com/MaybeMaru/Maru-Funkin/files/13997486/have.beat.able.chart.zip)

**Comment by AnAmmar** [comment]
the song is too big

**Comment by AnAmmar** [comment]
nvm here you go
[Inst.zip](https://github.com/MaybeMaru/Maru-Funkin/files/13997491/Inst.zip)
[Voices.zip](https://github.com/MaybeMaru/Maru-Funkin/files/13997492/Voices.zip)

**Comment by MaybeMaru** [comment]
> nvm here you go [Inst.zip](https://github.com/MaybeMaru/Maru-Funkin/files/13997491/Inst.zip) [Voices.zip](https://github.com/MaybeMaru/Maru-Funkin/files/13997492/Voices.zip)

ok so from what you sent me, the reason why the events appear 2 times is because the events are duplicated in the songMeta and hard jsons, you should remove the events from the hard chart, although they still appear 4 times
![image](https://github.com/MaybeMaru/Maru-Funkin/assets/97055307/845cc784-5213-4858-ad66-63d53500628a)
i checked the json file and the events are saved 4 times, so either the og chart is like this or something got messed up converting it?
![image](https://github.com/MaybeMaru/Maru-Funkin/assets/97055307/c963ee18-0250-41f7-a03d-c83da9b33bd4)

**Comment by AnAmmar** [comment]
Ok the Og chart have nothing wrong with it
![image_2024-01-21_214326663](https://github.com/MaybeMaru/Maru-Funkin/assets/98030475/e8d8b951-3df2-47f1-9c37-cb9ff1d33125)

**Comment by MaybeMaru** [comment]
coudl you send the og chart so i can test it on engine

**Comment by AnAmmar** [comment]
[unbeatable.json](https://github.com/MaybeMaru/Maru-Funkin/files/14001634/unbeatable.json)
here you go

**Comment by MaybeMaru** [comment]
> [unbeatable.json](https://github.com/MaybeMaru/Maru-Funkin/files/14001634/unbeatable.json) here you go

it seems to be loading correctly for me, heres the output i got
![image](https://github.com/MaybeMaru/Maru-Funkin/assets/97055307/48260b30-4453-44ab-9058-d6ad37f35fac)
[hard.json](https://github.com/MaybeMaru/Maru-Funkin/files/14001810/hard.json)

**Comment by AnAmmar** [comment]
Wait what. But how did I managed to get the repeating bug. Hmm I think I remember that it happened after I saved the chart and reopen the chart editor.

**Comment by MaybeMaru** [comment]
closed because im gonna rewrite the chart editor either way lmao
